<?php
declare(strict_types=1);

namespace Dictionary\PhpArray;


use Dictionary\BuilderInterface;
use Gettext\Translations;

class PhpArray implements BuilderInterface
{
    const FILE = __DIR__ . '/autogenerated-translations-uk.phpArray';

    final public function build(Translations $phrases): void
    {
        $phrases->toPhpArrayFile(self::FILE, ['includeHeaders' => false]);
    }
}